name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: npm install
      - name: Build production project
        run: npm run build:prod
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/archimeister757/my-react-app:latest \
            .
      - name: Push Docker image
        run: |
          docker push ghcr.io/archimeister757/my-react-app:latest
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting css
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()
      - name: Screenshot testing
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
